version: '3.3'

services:
  web:
    build: ./todo_list
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./todo_list:/usr/src/todo_list
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes: 
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=database

volumes:
  postgres_volume: